# cwl for package unicode-math, version 0.8c
# Copyright. 2016-
# Darcy Hu <hot123tea123@gmail.com>
#
#include:ifxetex
#include:ifluatex
#include:expl3
#include:uchartcat
#include:xparse
#include:l3keys2e
#include:fontspec
#include:fix-cm
#include:filehook
#
\usepackage{unicode-math}#u
\usepackage[options]{unicode-math}#u
\setmathfont{font name}
\setmathfont[font features]{font name}
\unimathsetup{keyval}#
#
#keyvals:\unimathsetup
math-style=#TeX,ISO,french,upright,literal
bold-style=#TeX,ISO,upright,literal
sans-style=#upright,italic,literal
nabla=#upright,italic,literal
partial=#upright,italic,literal
vargreek-shape=#TeX,unicode
colon=#literal,TeX
slash-delimiter=#ascii,frac,div
active-frac=#small,normalsize
range=
Style=
version=
script-font=
script-features=
sscript-font=
sscript-features=
#endkeyvals
# commands to select specific 'alphabets'
# within the unicode math font
\symnormal{alphabet}
\symliteral{alphabet}
\symbfup{alphabet}
\symbfit{alphabet}
\symsfup{alphabet}
\symsfit{alphabet}
\symbfsfup{alphabet}
\symbfsfit{alphabet}
\symbfsf{alphabet}
\symbb{alphabet}
\symbbit{alphabet}
\symscr{alphabet}
\symcal{alphabet}
\symbfcal{alphabet}
\symfrak{alphabet}
\symbffrack{alphabet}
\symup{alphabet}
\symsf{alphabet}
\symbf{alphabet}
\symtt{alphabet}
\symit{alphabet}
#
\mathnormal{text}
\mathbb{text}
\mathbbit{text}
\mathscr{text}
\mathbfscr{text}
\mathcal{text}
\mathbfcal{text}
\mathfrak{text}
\mathbffrak{text}
\mathbfup{text}
\mathbfit{text}
\mathsfup{text}
\mathsfit{text}
\mathbfsfup{text}
\mathbfsfit{text}
\mathbfsf{text}
#
\setmathfontface{cmd}{font name}#d
\setmathfontface{cmd}{font name}[font features]#d
\setmathfontface{cmd}{font name}[version = %<version name%>, font features]#d
\setoperatorfont{font macro}
\mathversion{version name}
#
#
# macros auto generate from unicode-math-table.tex
\mathexclam#*m
\mathoctothorpe#*m
\mathdollar#*m
\mathpercent#*m
\mathampersand#*m
\lparen#*m
\rparen#*m
\mathplus#*m
\mathcomma#*m
\mathperiod#*m
\mathslash#*m
\mathcolon#*m
\mathsemicolon#*m
\less#*m
\equal#*m
\greater#*m
\mathquestion#*m
\mathatsign#*m
\lbrack#*m
\backslash#*m
\rbrack#*m
\lbrace#*m
\vert#*m
\rbrace#*m
\mathsterling#*m
\mathyen#*m
\neg#*m
\pm#*m
\cdotp#*m
\times#*m
\matheth#*m
\div#*m
\Zbar#*m
\grave#*m
\acute#*m
\hat#*m
\widehat#*m
\tilde#*m
\widetilde#*m
\bar#*m
\overbar#*m
\breve#*m
\dot#*m
\ddot#*m
\ovhook#*m
\ocirc#*m
\check#*m
\candra#*m
\oturnedcomma#*m
\ocommatopright#*m
\droang#*m
\wideutilde#*m
\mathunderbar#*m
\not#*m
\underleftrightarrow#*m
\mupAlpha#*m
\mupBeta#*m
\mupGamma#*m
\mupDelta#*m
\mupEpsilon#*m
\mupZeta#*m
\mupEta#*m
\mupTheta#*m
\mupIota#*m
\mupKappa#*m
\mupLambda#*m
\mupMu#*m
\mupNu#*m
\mupXi#*m
\mupOmicron#*m
\mupPi#*m
\mupRho#*m
\mupSigma#*m
\mupTau#*m
\mupUpsilon#*m
\mupPhi#*m
\mupChi#*m
\mupPsi#*m
\mupOmega#*m
\mupalpha#*m
\mupbeta#*m
\mupgamma#*m
\mupdelta#*m
\mupepsilon#*m
\mupzeta#*m
\mupeta#*m
\muptheta#*m
\mupiota#*m
\mupkappa#*m
\muplambda#*m
\mupmu#*m
\mupnu#*m
\mupxi#*m
\mupomicron#*m
\muppi#*m
\muprho#*m
\mupvarsigma#*m
\mupsigma#*m
\muptau#*m
\mupupsilon#*m
\mupvarphi#*m
\mupchi#*m
\muppsi#*m
\mupomega#*m
\mupvarbeta#*m
\mupvartheta#*m
\mupphi#*m
\mupvarpi#*m
\upoldKoppa#*m
\upoldkoppa#*m
\upStigma#*m
\upstigma#*m
\upDigamma#*m
\updigamma#*m
\upKoppa#*m
\upkoppa#*m
\upSampi#*m
\upsampi#*m
\mupvarkappa#*m
\mupvarrho#*m
\mupvarTheta#*m
\mupvarepsilon#*m
\upbackepsilon#*m
\horizbar#*m
\Vert#*m
\twolowline#*m
\dagger#*m
\ddagger#*m
\smblkcircle#*m
\enleadertwodots#*m
\unicodeellipsis#*m
\prime#*m
\dprime#*m
\trprime#*m
\backprime#*m
\backdprime#*m
\backtrprime#*m
\caretinsert#*m
\Exclam#*m
\tieconcat#*m
\hyphenbullet#*m
\fracslash#*m
\Question#*m
\closure#*m
\qprime#*m
\euro#*m
\leftharpoonaccent#*m
\overleftharpoon#*m
\rightharpoonaccent#*m
\overrightharpoon#*m
\vertoverlay#*m
\overleftarrow#*m
\overrightarrow#*m
\vec#*m
\dddot#*m
\ddddot#*m
\enclosecircle#*m
\enclosesquare#*m
\enclosediamond#*m
\overleftrightarrow#*m
\enclosetriangle#*m
\annuity#*m
\threeunderdot#*m
\widebridgeabove#*m
\underrightharpoondown#*m
\underleftharpoondown#*m
\underleftarrow#*m
\underrightarrow#*m
\asteraccent#*m
\BbbC#*m
\Eulerconst#*m
\mscrg#*m
\mscrH#*m
\mfrakH#*m
\BbbH#*m
\Planckconst#*m
\hslash#*m
\mscrI#*m
\Im#*m
\mscrL#*m
\ell#*m
\BbbN#*m
\wp#*m
\BbbP#*m
\BbbQ#*m
\mscrR#*m
\Re#*m
\BbbR#*m
\BbbZ#*m
\mho#*m
\mfrakZ#*m
\turnediota#*m
\Angstrom#*m
\mscrB#*m
\mfrakC#*m
\mscre#*m
\mscrE#*m
\mscrF#*m
\Finv#*m
\mscrM#*m
\mscro#*m
\aleph#*m
\beth#*m
\gimel#*m
\daleth#*m
\Bbbpi#*m
\Bbbgamma#*m
\BbbGamma#*m
\BbbPi#*m
\Bbbsum#*m
\Game#*m
\sansLturned#*m
\sansLmirrored#*m
\Yup#*m
\mitBbbD#*m
\mitBbbd#*m
\mitBbbe#*m
\mitBbbi#*m
\mitBbbj#*m
\PropertyLine#*m
\upand#*m
\leftarrow#*m
\uparrow#*m
\rightarrow#*m
\downarrow#*m
\leftrightarrow#*m
\updownarrow#*m
\nwarrow#*m
\nearrow#*m
\searrow#*m
\swarrow#*m
\nleftarrow#*m
\nrightarrow#*m
\leftwavearrow#*m
\rightwavearrow#*m
\twoheadleftarrow#*m
\twoheaduparrow#*m
\twoheadrightarrow#*m
\twoheaddownarrow#*m
\leftarrowtail#*m
\rightarrowtail#*m
\mapsfrom#*m
\mapsup#*m
\mapsto#*m
\mapsdown#*m
\updownarrowbar#*m
\hookleftarrow#*m
\hookrightarrow#*m
\looparrowleft#*m
\looparrowright#*m
\leftrightsquigarrow#*m
\nleftrightarrow#*m
\downzigzagarrow#*m
\Lsh#*m
\Rsh#*m
\Ldsh#*m
\Rdsh#*m
\linefeed#*m
\carriagereturn#*m
\curvearrowleft#*m
\curvearrowright#*m
\barovernorthwestarrow#*m
\barleftarrowrightarrowbar}#*m
\acwopencirclearrow#*m
\cwopencirclearrow#*m
\leftharpoonup#*m
\leftharpoondown#*m
\upharpoonright#*m
\upharpoonleft#*m
\rightharpoonup#*m
\rightharpoondown#*m
\downharpoonright#*m
\downharpoonleft#*m
\rightleftarrows#*m
\updownarrows#*m
\leftrightarrows#*m
\leftleftarrows#*m
\upuparrows#*m
\rightrightarrows#*m
\downdownarrows#*m
\leftrightharpoons#*m
\rightleftharpoons#*m
\nLeftarrow#*m
\nLeftrightarrow#*m
\nRightarrow#*m
\Leftarrow#*m
\Uparrow#*m
\Rightarrow#*m
\Downarrow#*m
\Leftrightarrow#*m
\Updownarrow#*m
\Nwarrow#*m
\Nearrow#*m
\Searrow#*m
\Swarrow#*m
\Lleftarrow#*m
\Rrightarrow#*m
\leftsquigarrow#*m
\rightsquigarrow#*m
\nHuparrow#*m
\nHdownarrow#*m
\leftdasharrow#*m
\updasharrow#*m
\rightdasharrow#*m
\downdasharrow#*m
\barleftarrow#*m
\rightarrowbar#*m
\leftwhitearrow#*m
\upwhitearrow#*m
\rightwhitearrow#*m
\downwhitearrow#*m
\whitearrowupfrombar#*m
\circleonrightarrow#*m
\downuparrows#*m
\rightthreearrows#*m
\nvleftarrow#*m
\nvrightarrow#*m
\nvleftrightarrow#*m
\nVleftarrow#*m
\nVrightarrow#*m
\nVleftrightarrow#*m
\leftarrowtriangle#*m
\rightarrowtriangle#*m
\leftrightarrowtriangle#*m
\forall#*m
\complement#*m
\partial#*m
\exists#*m
\nexists#*m
\varnothing#*m
\increment#*m
\nabla#*m
\in#*m
\notin#*m
\smallin#*m
\ni#*m
\nni#*m
\smallni#*m
\QED#*m
\prod#*m
\coprod#*m
\sum#*m
\minus#*m
\mp#*m
\dotplus#*m
\divslash#*m
\smallsetminus#*m
\ast#*m
\vysmwhtcircle#*m
\vysmblkcircle#*m
\sqrt#*m
\cuberoot#*m
\fourthroot#*m
\propto#*m
\infty#*m
\rightangle#*m
\angle#*m
\measuredangle#*m
\sphericalangle#*m
\mid#*m
\nmid#*m
\parallel#*m
\nparallel#*m
\wedge#*m
\vee#*m
\cap#*m
\cup#*m
\int#*m
\iint#*m
\iiint#*m
\oint#*m
\oiint#*m
\oiiint#*m
\intclockwise#*m
\varointclockwise#*m
\ointctrclockwise#*m
\therefore#*m
\because#*m
\mathratio#*m
\Colon#*m
\dotminus#*m
\dashcolon#*m
\dotsminusdots#*m
\kernelcontraction#*m
\sim#*m
\backsim#*m
\invlazys#*m
\sinewave#*m
\wr#*m
\nsim#*m
\eqsim#*m
\simeq#*m
\nsime#*m
\cong#*m
\simneqq#*m
\ncong#*m
\approx#*m
\napprox#*m
\approxeq#*m
\approxident#*m
\backcong#*m
\asymp#*m
\Bumpeq#*m
\bumpeq#*m
\doteq#*m
\Doteq#*m
\fallingdotseq#*m
\risingdotseq#*m
\coloneq#*m
\eqcolon#*m
\eqcirc#*m
\circeq#*m
\arceq#*m
\wedgeq#*m
\veeeq#*m
\stareq#*m
\triangleq#*m
\eqdef#*m
\measeq#*m
\questeq#*m
\ne#*m
\equiv#*m
\nequiv#*m
\Equiv#*m
\leq#*m
\geq#*m
\leqq#*m
\geqq#*m
\lneqq#*m
\gneqq#*m
\ll#*m
\gg#*m
\between#*m
\nasymp#*m
\nless#*m
\ngtr#*m
\nleq#*m
\ngeq#*m
\lesssim#*m
\gtrsim#*m
\nlesssim#*m
\ngtrsim#*m
\lessgtr#*m
\gtrless#*m
\nlessgtr#*m
\ngtrless#*m
\prec#*m
\succ#*m
\preccurlyeq#*m
\succcurlyeq#*m
\precsim#*m
\succsim#*m
\nprec#*m
\nsucc#*m
\subset#*m
\supset#*m
\nsubset#*m
\nsupset#*m
\subseteq#*m
\supseteq#*m
\nsubseteq#*m
\nsupseteq#*m
\subsetneq#*m
\supsetneq#*m
\cupleftarrow#*m
\cupdot#*m
\uplus#*m
\sqsubset#*m
\sqsupset#*m
\sqsubseteq#*m
\sqsupseteq#*m
\sqcap#*m
\sqcup#*m
\oplus#*m
\ominus#*m
\otimes#*m
\oslash#*m
\odot#*m
\circledcirc#*m
\circledast#*m
\circledequal#*m
\circleddash#*m
\boxplus#*m
\boxminus#*m
\boxtimes#*m
\boxdot#*m
\vdash#*m
\dashv#*m
\top#*m
\bot#*m
\assert#*m
\models#*m
\vDash#*m
\Vdash#*m
\Vvdash#*m
\VDash#*m
\nvdash#*m
\nvDash#*m
\nVdash#*m
\nVDash#*m
\prurel#*m
\scurel#*m
\vartriangleleft#*m
\vartriangleright#*m
\trianglelefteq#*m
\trianglerighteq#*m
\origof#*m
\imageof#*m
\multimap#*m
\hermitmatrix#*m
\intercal#*m
\veebar#*m
\barwedge#*m
\barvee#*m
\measuredrightangle#*m
\varlrtriangle#*m
\bigwedge#*m
\bigvee#*m
\bigcap#*m
\bigcup#*m
\smwhtdiamond#*m
\cdot#*m
\star#*m
\divideontimes#*m
\bowtie#*m
\ltimes#*m
\rtimes#*m
\leftthreetimes#*m
\rightthreetimes#*m
\backsimeq#*m
\curlyvee#*m
\curlywedge#*m
\Subset#*m
\Supset#*m
\Cap#*m
\Cup#*m
\pitchfork#*m
\equalparallel#*m
\lessdot#*m
\gtrdot#*m
\lll#*m
\ggg#*m
\lesseqgtr#*m
\gtreqless#*m
\eqless#*m
\eqgtr#*m
\curlyeqprec#*m
\curlyeqsucc#*m
\npreccurlyeq#*m
\nsucccurlyeq#*m
\nsqsubseteq#*m
\nsqsupseteq#*m
\sqsubsetneq#*m
\sqsupsetneq#*m
\lnsim#*m
\gnsim#*m
\precnsim#*m
\succnsim#*m
\nvartriangleleft#*m
\nvartriangleright#*m
\ntrianglelefteq#*m
\ntrianglerighteq#*m
\vdots#*m
\unicodecdots#*m
\adots#*m
\ddots#*m
\disin#*m
\varisins#*m
\isins#*m
\isindot#*m
\varisinobar#*m
\isinobar#*m
\isinvb#*m
\isinE#*m
\nisd#*m
\varnis#*m
\nis#*m
\varniobar#*m
\niobar#*m
\bagmember#*m
\diameter#*m
\house#*m
\varbarwedge#*m
\vardoublebarwedge#*m
\lceil#*m
\rceil#*m
\lfloor#*m
\rfloor#*m
\invnot#*m
\sqlozenge#*m
\profline#*m
\profsurf#*m
\viewdata#*m
\turnednot#*m
\ulcorner#*m
\urcorner#*m
\llcorner#*m
\lrcorner#*m
\inttop#*m
\intbottom#*m
\frown#*m
\smile#*m
\varhexagonlrbonds#*m
\conictaper#*m
\topbot#*m
\obar#*m
\APLnotslash#*m
\APLnotbackslash#*m
\APLboxupcaret#*m
\APLboxquestion#*m
\rangledownzigzagarrow#*m
\hexagon#*m
\lparenuend#*m
\lparenextender#*m
\lparenlend#*m
\rparenuend#*m
\rparenextender#*m
\rparenlend#*m
\lbrackuend#*m
\lbrackextender#*m
\lbracklend#*m
\rbrackuend#*m
\rbrackextender#*m
\rbracklend#*m
\lbraceuend#*m
\lbracemid#*m
\lbracelend#*m
\vbraceextender#*m
\rbraceuend#*m
\rbracemid#*m
\rbracelend#*m
\intextender#*m
\harrowextender#*m
\lmoustache#*m
\rmoustache#*m
\sumtop#*m
\sumbottom#*m
\overbracket#*m
\underbracket#*m
\bbrktbrk#*m
\sqrtbottom#*m
\lvboxline#*m
\rvboxline#*m
\varcarriagereturn#*m
\overparen#*m
\underparen#*m
\overbrace#*m
\underbrace#*m
\obrbrak#*m
\ubrbrak#*m
\trapezium#*m
\benzenr#*m
\strns#*m
\fltns#*m
\accurrent#*m
\elinters#*m
\blanksymbol#*m
\mathvisiblespace#*m
\bdtriplevdash#*m
\blockuphalf#*m
\blocklowhalf#*m
\blockfull#*m
\blocklefthalf#*m
\blockrighthalf#*m
\blockqtrshaded#*m
\blockhalfshaded#*m
\blockthreeqtrshaded#*m
\mdlgblksquare#*m
\mdlgwhtsquare#*m
\squoval#*m
\blackinwhitesquare#*m
\squarehfill#*m
\squarevfill#*m
\squarehvfill#*m
\squarenwsefill#*m
\squareneswfill#*m
\squarecrossfill#*m
\smblksquare#*m
\smwhtsquare#*m
\hrectangleblack#*m
\hrectangle#*m
\vrectangleblack#*m
\vrectangle#*m
\parallelogramblack#*m
\parallelogram#*m
\bigblacktriangleup#*m
\bigtriangleup#*m
\blacktriangle#*m
\vartriangle#*m
\blacktriangleright#*m
\triangleright#*m
\smallblacktriangleright#*m
\smalltriangleright#*m
\blackpointerright#*m
\whitepointerright#*m
\bigblacktriangledown#*m
\bigtriangledown#*m
\blacktriangledown#*m
\triangledown#*m
\blacktriangleleft#*m
\triangleleft#*m
\smallblacktriangleleft#*m
\smalltriangleleft#*m
\blackpointerleft#*m
\whitepointerleft#*m
\mdlgblkdiamond#*m
\mdlgwhtdiamond#*m
\blackinwhitediamond#*m
\fisheye#*m
\mdlgwhtlozenge#*m
\mdlgwhtcircle#*m
\dottedcircle#*m
\circlevertfill#*m
\bullseye#*m
\mdlgblkcircle#*m
\circlelefthalfblack#*m
\circlerighthalfblack#*m
\circlebottomhalfblack#*m
\circletophalfblack#*m
\circleurquadblack#*m
\blackcircleulquadwhite#*m
\blacklefthalfcircle#*m
\blackrighthalfcircle#*m
\inversebullet#*m
\inversewhitecircle#*m
\invwhiteupperhalfcircle#*m
\invwhitelowerhalfcircle#*m
\ularc#*m
\urarc#*m
\lrarc#*m
\llarc#*m
\topsemicircle#*m
\botsemicircle#*m
\lrblacktriangle#*m
\llblacktriangle#*m
\ulblacktriangle#*m
\urblacktriangle#*m
\smwhtcircle#*m
\squareleftblack#*m
\squarerightblack#*m
\squareulblack#*m
\squarelrblack#*m
\boxbar#*m
\trianglecdot#*m
\triangleleftblack#*m
\trianglerightblack#*m
\lgwhtcircle#*m
\squareulquad#*m
\squarellquad#*m
\squarelrquad#*m
\squareurquad#*m
\circleulquad#*m
\circlellquad#*m
\circlelrquad#*m
\circleurquad#*m
\ultriangle#*m
\urtriangle#*m
\lltriangle#*m
\mdwhtsquare#*m
\mdblksquare#*m
\mdsmwhtsquare#*m
\mdsmblksquare#*m
\lrtriangle#*m
\bigstar#*m
\bigwhitestar#*m
\astrosun#*m
\danger#*m
\blacksmiley#*m
\sun#*m
\rightmoon#*m
\leftmoon#*m
\female#*m
\male#*m
\spadesuit#*m
\heartsuit#*m
\diamondsuit#*m
\clubsuit#*m
\varspadesuit#*m
\varheartsuit#*m
\vardiamondsuit#*m
\varclubsuit#*m
\quarternote#*m
\eighthnote#*m
\twonotes#*m
\flat#*m
\natural#*m
\sharp#*m
\acidfree#*m
\dicei#*m
\diceii#*m
\diceiii#*m
\diceiv#*m
\dicev#*m
\dicevi#*m
\circledrightdot#*m
\circledtwodots#*m
\blackcircledrightdot#*m
\blackcircledtwodots#*m
\Hermaphrodite#*m
\mdwhtcircle#*m
\mdblkcircle#*m
\mdsmwhtcircle#*m
\neuter#*m
\checkmark#*m
\maltese#*m
\circledstar#*m
\varstar#*m
\dingasterisk#*m
\lbrbrak#*m
\rbrbrak#*m
\draftingarrow#*m
\threedangle#*m
\whiteinwhitetriangle#*m
\perp#*m
\subsetcirc#*m
\supsetcirc#*m
\lbag#*m
\rbag#*m
\veedot#*m
\bsolhsub#*m
\suphsol#*m
\longdivision#*m
\diamondcdot#*m
\wedgedot#*m
\upin#*m
\pullback#*m
\pushout#*m
\leftouterjoin#*m
\rightouterjoin#*m
\fullouterjoin#*m
\bigbot#*m
\bigtop#*m
\DashVDash#*m
\dashVdash#*m
\multimapinv#*m
\vlongdash#*m
\longdashv#*m
\cirbot#*m
\lozengeminus#*m
\concavediamond#*m
\concavediamondtickleft#*m
\concavediamondtickright#*m
\whitesquaretickleft#*m
\whitesquaretickright#*m
\lBrack#*m
\rBrack#*m
\langle#*m
\rangle#*m
\lAngle#*m
\rAngle#*m
\Lbrbrak#*m
\Rbrbrak#*m
\lgroup#*m
\rgroup#*m
\UUparrow#*m
\DDownarrow#*m
\acwgapcirclearrow#*m
\cwgapcirclearrow#*m
\rightarrowonoplus#*m
\longleftarrow#*m
\longrightarrow#*m
\longleftrightarrow#*m
\Longleftarrow#*m
\Longrightarrow#*m
\Longleftrightarrow#*m
\longmapsfrom#*m
\longmapsto#*m
\Longmapsfrom#*m
\Longmapsto#*m
\longrightsquigarrow#*m
\nvtwoheadrightarrow#*m
\nVtwoheadrightarrow#*m
\nvLeftarrow#*m
\nvRightarrow#*m
\nvLeftrightarrow#*m
\twoheadmapsto#*m
\Mapsfrom#*m
\Mapsto#*m
\downarrowbarred#*m
\uparrowbarred#*m
\Uuparrow#*m
\Ddownarrow#*m
\leftbkarrow#*m
\rightbkarrow#*m
\leftdbkarrow#*m
\dbkarrow#*m
\drbkarrow#*m
\rightdotarrow#*m
\baruparrow#*m
\downarrowbar#*m
\nvrightarrowtail#*m
\nVrightarrowtail#*m
\twoheadrightarrowtail#*m
\nvtwoheadrightarrowtail#*m
\nVtwoheadrightarrowtail#*m
\lefttail#*m
\righttail#*m
\leftdbltail#*m
\rightdbltail#*m
\diamondleftarrow#*m
\rightarrowdiamond#*m
\diamondleftarrowbar#*m
\barrightarrowdiamond#*m
\nwsearrow#*m
\neswarrow#*m
\hknwarrow#*m
\hknearrow#*m
\hksearrow#*m
\hkswarrow#*m
\tona#*m
\toea#*m
\tosa#*m
\towa#*m
\rdiagovfdiag#*m
\fdiagovrdiag#*m
\seovnearrow#*m
\neovsearrow#*m
\fdiagovnearrow#*m
\rdiagovsearrow#*m
\neovnwarrow#*m
\nwovnearrow#*m
\rightcurvedarrow#*m
\uprightcurvearrow#*m
\downrightcurvedarrow#*m
\leftdowncurvedarrow#*m
\rightdowncurvedarrow#*m
\cwrightarcarrow#*m
\acwleftarcarrow#*m
\acwoverarcarrow#*m
\acwunderarcarrow#*m
\curvearrowrightminus#*m
\curvearrowleftplus#*m
\cwundercurvearrow#*m
\ccwundercurvearrow#*m
\acwcirclearrow#*m
\cwcirclearrow#*m
\rightarrowshortleftarrow#*m
\leftarrowshortrightarrow#*m
\shortrightarrowleftarrow#*m
\rightarrowplus#*m
\leftarrowplus#*m
\rightarrowx#*m
\leftrightarrowcircle#*m
\twoheaduparrowcircle#*m
\leftrightharpoonupdown#*m
\leftrightharpoondownup#*m
\updownharpoonrightleft#*m
\updownharpoonleftright#*m
\leftrightharpoonupup#*m
\updownharpoonrightright#*m
\leftrightharpoondowndown#*m
\updownharpoonleftleft#*m
\barleftharpoonup#*m
\rightharpoonupbar#*m
\barupharpoonright#*m
\downharpoonrightbar#*m
\barleftharpoondown#*m
\rightharpoondownbar#*m
\barupharpoonleft#*m
\downharpoonleftbar#*m
\leftharpoonupbar#*m
\barrightharpoonup#*m
\upharpoonrightbar#*m
\bardownharpoonright#*m
\leftharpoondownbar#*m
\barrightharpoondown#*m
\upharpoonleftbar#*m
\bardownharpoonleft#*m
\leftharpoonsupdown#*m
\upharpoonsleftright#*m
\rightharpoonsupdown#*m
\downharpoonsleftright#*m
\leftrightharpoonsup#*m
\leftrightharpoonsdown#*m
\rightleftharpoonsup#*m
\rightleftharpoonsdown#*m
\leftharpoonupdash#*m
\dashleftharpoondown#*m
\rightharpoonupdash#*m
\dashrightharpoondown#*m
\updownharpoonsleftright#*m
\downupharpoonsleftright#*m
\rightimply#*m
\equalrightarrow#*m
\similarrightarrow#*m
\leftarrowsimilar#*m
\rightarrowsimilar#*m
\rightarrowapprox#*m
\ltlarr#*m
\leftarrowless#*m
\gtrarr#*m
\subrarr#*m
\leftarrowsubset#*m
\suplarr#*m
\leftfishtail#*m
\rightfishtail#*m
\upfishtail#*m
\downfishtail#*m
\Vvert#*m
\mdsmblkcircle#*m
\typecolon#*m
\lBrace#*m
\rBrace#*m
\lParen#*m
\rParen#*m
\llparenthesis#*m
\rrparenthesis#*m
\llangle#*m
\rrangle#*m
\lbrackubar#*m
\rbrackubar#*m
\lbrackultick#*m
\rbracklrtick#*m
\lbracklltick#*m
\rbrackurtick#*m
\langledot#*m
\rangledot#*m
\lparenless#*m
\rparengtr#*m
\Lparengtr#*m
\Rparenless#*m
\lblkbrbrak#*m
\rblkbrbrak#*m
\fourvdots#*m
\vzigzag#*m
\measuredangleleft#*m
\rightanglesqr#*m
\rightanglemdot#*m
\angles#*m
\angdnr#*m
\gtlpar#*m
\sphericalangleup#*m
\turnangle#*m
\revangle#*m
\angleubar#*m
\revangleubar#*m
\wideangledown#*m
\wideangleup#*m
\measanglerutone#*m
\measanglelutonw#*m
\measanglerdtose#*m
\measangleldtosw#*m
\measangleurtone#*m
\measangleultonw#*m
\measangledrtose#*m
\measangledltosw#*m
\revemptyset#*m
\emptysetobar#*m
\emptysetocirc#*m
\emptysetoarr#*m
\emptysetoarrl#*m
\circlehbar#*m
\circledvert#*m
\circledparallel#*m
\obslash#*m
\operp#*m
\obot#*m
\olcross#*m
\odotslashdot#*m
\uparrowoncircle#*m
\circledwhitebullet#*m
\circledbullet#*m
\olessthan#*m
\ogreaterthan#*m
\cirscir#*m
\cirE#*m
\boxdiag#*m
\boxbslash#*m
\boxast#*m
\boxcircle#*m
\boxbox#*m
\boxonbox#*m
\triangleodot#*m
\triangleubar#*m
\triangles#*m
\triangleserifs#*m
\rtriltri#*m
\ltrivb#*m
\vbrtri#*m
\lfbowtie#*m
\rfbowtie#*m
\fbowtie#*m
\lftimes#*m
\rftimes#*m
\hourglass#*m
\blackhourglass#*m
\lvzigzag#*m
\rvzigzag#*m
\Lvzigzag#*m
\Rvzigzag#*m
\iinfin#*m
\tieinfty#*m
\nvinfty#*m
\dualmap#*m
\laplac#*m
\lrtriangleeq#*m
\shuffle#*m
\eparsl#*m
\smeparsl#*m
\eqvparsl#*m
\gleichstark#*m
\thermod#*m
\downtriangleleftblack#*m
\downtrianglerightblack#*m
\blackdiamonddownarrow#*m
\mdlgblklozenge#*m
\circledownarrow#*m
\blackcircledownarrow#*m
\errbarsquare#*m
\errbarblacksquare#*m
\errbardiamond#*m
\errbarblackdiamond#*m
\errbarcircle#*m
\errbarblackcircle#*m
\ruledelayed#*m
\setminus#*m
\dsol#*m
\rsolbar#*m
\xsol#*m
\xbsol#*m
\doubleplus#*m
\tripleplus#*m
\lcurvyangle#*m
\rcurvyangle#*m
\tplus#*m
\tminus#*m
\bigodot#*m
\bigoplus#*m
\bigotimes#*m
\bigcupdot#*m
\biguplus#*m
\bigsqcap#*m
\bigsqcup#*m
\conjquant#*m
\disjquant#*m
\bigtimes#*m
\modtwosum#*m
\sumint#*m
\iiiint#*m
\intbar#*m
\intBar#*m
\fint#*m
\cirfnint#*m
\awint#*m
\rppolint#*m
\scpolint#*m
\npolint#*m
\pointint#*m
\sqint#*m
\intlarhk#*m
\intx#*m
\intcap#*m
\intcup#*m
\upint#*m
\lowint#*m
\Join#*m
\bigtriangleleft#*m
\zcmp#*m
\zpipe#*m
\zproject#*m
\ringplus#*m
\plushat#*m
\simplus#*m
\plusdot#*m
\plussim#*m
\plussubtwo#*m
\plustrif#*m
\commaminus#*m
\minusdot#*m
\minusfdots#*m
\minusrdots#*m
\opluslhrim#*m
\oplusrhrim#*m
\vectimes#*m
\dottimes#*m
\timesbar#*m
\btimes#*m
\smashtimes#*m
\otimeslhrim#*m
\otimesrhrim#*m
\otimeshat#*m
\Otimes#*m
\odiv#*m
\triangleplus#*m
\triangleminus#*m
\triangletimes#*m
\intprod#*m
\intprodr#*m
\fcmp#*m
\amalg#*m
\capdot#*m
\uminus#*m
\barcup#*m
\barcap#*m
\capwedge#*m
\cupvee#*m
\cupovercap#*m
\capovercup#*m
\cupbarcap#*m
\capbarcup#*m
\twocups#*m
\twocaps#*m
\closedvarcup#*m
\closedvarcap#*m
\Sqcap#*m
\Sqcup#*m
\closedvarcupsmashprod#*m
\wedgeodot#*m
\veeodot#*m
\Wedge#*m
\Vee#*m
\wedgeonwedge#*m
\veeonvee#*m
\bigslopedvee#*m
\bigslopedwedge#*m
\veeonwedge#*m
\wedgemidvert#*m
\veemidvert#*m
\midbarwedge#*m
\midbarvee#*m
\doublebarwedge#*m
\wedgebar#*m
\wedgedoublebar#*m
\varveebar#*m
\doublebarvee#*m
\veedoublebar#*m
\dsub#*m
\rsub#*m
\eqdot#*m
\dotequiv#*m
\equivVert#*m
\equivVvert#*m
\dotsim#*m
\simrdots#*m
\simminussim#*m
\congdot#*m
\asteq#*m
\hatapprox#*m
\approxeqq#*m
\eqqplus#*m
\pluseqq#*m
\eqqsim#*m
\Coloneq#*m
\eqeq#*m
\eqeqeq#*m
\ddotseq#*m
\equivDD#*m
\ltcir#*m
\gtcir#*m
\ltquest#*m
\gtquest#*m
\leqslant#*m
\geqslant#*m
\lesdot#*m
\gesdot#*m
\lesdoto#*m
\gesdoto#*m
\lesdotor#*m
\gesdotol#*m
\lessapprox#*m
\gtrapprox#*m
\lneq#*m
\gneq#*m
\lnapprox#*m
\gnapprox#*m
\lesseqqgtr#*m
\gtreqqless#*m
\lsime#*m
\gsime#*m
\lsimg#*m
\gsiml#*m
\lgE#*m
\glE#*m
\lesges#*m
\gesles#*m
\eqslantless#*m
\eqslantgtr#*m
\elsdot#*m
\egsdot#*m
\eqqless#*m
\eqqgtr#*m
\eqqslantless#*m
\eqqslantgtr#*m
\simless#*m
\simgtr#*m
\simlE#*m
\simgE#*m
\Lt#*m
\Gt#*m
\partialmeetcontraction#*m
\glj#*m
\gla#*m
\ltcc#*m
\gtcc#*m
\lescc#*m
\gescc#*m
\smt#*m
\lat#*m
\smte#*m
\late#*m
\bumpeqq#*m
\preceq#*m
\succeq#*m
\precneq#*m
\succneq#*m
\preceqq#*m
\succeqq#*m
\precneqq#*m
\succneqq#*m
\precapprox#*m
\succapprox#*m
\precnapprox#*m
\succnapprox#*m
\Prec#*m
\Succ#*m
\subsetdot#*m
\supsetdot#*m
\subsetplus#*m
\supsetplus#*m
\submult#*m
\supmult#*m
\subedot#*m
\supedot#*m
\subseteqq#*m
\supseteqq#*m
\subsim#*m
\supsim#*m
\subsetapprox#*m
\supsetapprox#*m
\subsetneqq#*m
\supsetneqq#*m
\lsqhook#*m
\rsqhook#*m
\csub#*m
\csup#*m
\csube#*m
\csupe#*m
\subsup#*m
\supsub#*m
\subsub#*m
\supsup#*m
\suphsub#*m
\supdsub#*m
\forkv#*m
\topfork#*m
\mlcp#*m
\forks#*m
\forksnot#*m
\shortlefttack#*m
\shortdowntack#*m
\shortuptack#*m
\perps#*m
\vDdash#*m
\dashV#*m
\Dashv#*m
\DashV#*m
\varVdash#*m
\Barv#*m
\vBar#*m
\vBarv#*m
\barV#*m
\Vbar#*m
\Not#*m
\bNot#*m
\revnmid#*m
\cirmid#*m
\midcir#*m
\topcir#*m
\nhpar#*m
\parsim#*m
\interleave#*m
\nhVvert#*m
\threedotcolon#*m
\lllnest#*m
\gggnest#*m
\leqqslant#*m
\geqqslant#*m
\trslash#*m
\biginterleave#*m
\sslash#*m
\talloblong#*m
\bigtalloblong#*m
\squaretopblack#*m
\squarebotblack#*m
\squareurblack#*m
\squarellblack#*m
\diamondleftblack#*m
\diamondrightblack#*m
\diamondtopblack#*m
\diamondbotblack#*m
\dottedsquare#*m
\lgblksquare#*m
\lgwhtsquare#*m
\vysmblksquare#*m
\vysmwhtsquare#*m
\pentagonblack#*m
\pentagon#*m
\varhexagon#*m
\varhexagonblack#*m
\hexagonblack#*m
\lgblkcircle#*m
\mdblkdiamond#*m
\mdwhtdiamond#*m
\mdblklozenge#*m
\mdwhtlozenge#*m
\smblkdiamond#*m
\smblklozenge#*m
\smwhtlozenge#*m
\blkhorzoval#*m
\whthorzoval#*m
\blkvertoval#*m
\whtvertoval#*m
\circleonleftarrow#*m
\leftthreearrows#*m
\leftarrowonoplus#*m
\longleftsquigarrow#*m
\nvtwoheadleftarrow#*m
\nVtwoheadleftarrow#*m
\twoheadmapsfrom#*m
\twoheadleftdbkarrow#*m
\leftdotarrow#*m
\nvleftarrowtail#*m
\nVleftarrowtail#*m
\twoheadleftarrowtail#*m
\nvtwoheadleftarrowtail#*m
\nVtwoheadleftarrowtail#*m
\leftarrowx#*m
\leftcurvedarrow#*m
\equalleftarrow#*m
\bsimilarleftarrow#*m
\leftarrowbackapprox#*m
\rightarrowgtr#*m
\rightarrowsupset#*m
\LLeftarrow#*m
\RRightarrow#*m
\bsimilarrightarrow#*m
\rightarrowbackapprox#*m
\similarleftarrow#*m
\leftarrowapprox#*m
\leftarrowbsimilar#*m
\rightarrowbsimilar#*m
\medwhitestar#*m
\medblackstar#*m
\smwhitestar#*m
\rightpentagonblack#*m
\rightpentagon#*m
\postalmark#*m
\hzigzag#*m
\mbfA#*m
\mbfB#*m
\mbfC#*m
\mbfD#*m
\mbfE#*m
\mbfF#*m
\mbfG#*m
\mbfH#*m
\mbfI#*m
\mbfJ#*m
\mbfK#*m
\mbfL#*m
\mbfM#*m
\mbfN#*m
\mbfO#*m
\mbfP#*m
\mbfQ#*m
\mbfR#*m
\mbfS#*m
\mbfT#*m
\mbfU#*m
\mbfV#*m
\mbfW#*m
\mbfX#*m
\mbfY#*m
\mbfZ#*m
\mbfa#*m
\mbfb#*m
\mbfc#*m
\mbfd#*m
\mbfe#*m
\mbff#*m
\mbfg#*m
\mbfh#*m
\mbfi#*m
\mbfj#*m
\mbfk#*m
\mbfl#*m
\mbfm#*m
\mbfn#*m
\mbfo#*m
\mbfp#*m
\mbfq#*m
\mbfr#*m
\mbfs#*m
\mbft#*m
\mbfu#*m
\mbfv#*m
\mbfw#*m
\mbfx#*m
\mbfy#*m
\mbfz#*m
\mitA#*m
\mitB#*m
\mitC#*m
\mitD#*m
\mitE#*m
\mitF#*m
\mitG#*m
\mitH#*m
\mitI#*m
\mitJ#*m
\mitK#*m
\mitL#*m
\mitM#*m
\mitN#*m
\mitO#*m
\mitP#*m
\mitQ#*m
\mitR#*m
\mitS#*m
\mitT#*m
\mitU#*m
\mitV#*m
\mitW#*m
\mitX#*m
\mitY#*m
\mitZ#*m
\mita#*m
\mitb#*m
\mitc#*m
\mitd#*m
\mite#*m
\mitf#*m
\mitg#*m
\miti#*m
\mitj#*m
\mitk#*m
\mitl#*m
\mitm#*m
\mitn#*m
\mito#*m
\mitp#*m
\mitq#*m
\mitr#*m
\mits#*m
\mitt#*m
\mitu#*m
\mitv#*m
\mitw#*m
\mitx#*m
\mity#*m
\mitz#*m
\mbfitA#*m
\mbfitB#*m
\mbfitC#*m
\mbfitD#*m
\mbfitE#*m
\mbfitF#*m
\mbfitG#*m
\mbfitH#*m
\mbfitI#*m
\mbfitJ#*m
\mbfitK#*m
\mbfitL#*m
\mbfitM#*m
\mbfitN#*m
\mbfitO#*m
\mbfitP#*m
\mbfitQ#*m
\mbfitR#*m
\mbfitS#*m
\mbfitT#*m
\mbfitU#*m
\mbfitV#*m
\mbfitW#*m
\mbfitX#*m
\mbfitY#*m
\mbfitZ#*m
\mbfita#*m
\mbfitb#*m
\mbfitc#*m
\mbfitd#*m
\mbfite#*m
\mbfitf#*m
\mbfitg#*m
\mbfith#*m
\mbfiti#*m
\mbfitj#*m
\mbfitk#*m
\mbfitl#*m
\mbfitm#*m
\mbfitn#*m
\mbfito#*m
\mbfitp#*m
\mbfitq#*m
\mbfitr#*m
\mbfits#*m
\mbfitt#*m
\mbfitu#*m
\mbfitv#*m
\mbfitw#*m
\mbfitx#*m
\mbfity#*m
\mbfitz#*m
\mscrA#*m
\mscrC#*m
\mscrD#*m
\mscrG#*m
\mscrJ#*m
\mscrK#*m
\mscrN#*m
\mscrO#*m
\mscrP#*m
\mscrQ#*m
\mscrS#*m
\mscrT#*m
\mscrU#*m
\mscrV#*m
\mscrW#*m
\mscrX#*m
\mscrY#*m
\mscrZ#*m
\mscra#*m
\mscrb#*m
\mscrc#*m
\mscrd#*m
\mscrf#*m
\mscrh#*m
\mscri#*m
\mscrj#*m
\mscrk#*m
\mscrl#*m
\mscrm#*m
\mscrn#*m
\mscrp#*m
\mscrq#*m
\mscrr#*m
\mscrs#*m
\mscrt#*m
\mscru#*m
\mscrv#*m
\mscrw#*m
\mscrx#*m
\mscry#*m
\mscrz#*m
\mbfscrA#*m
\mbfscrB#*m
\mbfscrC#*m
\mbfscrD#*m
\mbfscrE#*m
\mbfscrF#*m
\mbfscrG#*m
\mbfscrH#*m
\mbfscrI#*m
\mbfscrJ#*m
\mbfscrK#*m
\mbfscrL#*m
\mbfscrM#*m
\mbfscrN#*m
\mbfscrO#*m
\mbfscrP#*m
\mbfscrQ#*m
\mbfscrR#*m
\mbfscrS#*m
\mbfscrT#*m
\mbfscrU#*m
\mbfscrV#*m
\mbfscrW#*m
\mbfscrX#*m
\mbfscrY#*m
\mbfscrZ#*m
\mbfscra#*m
\mbfscrb#*m
\mbfscrc#*m
\mbfscrd#*m
\mbfscre#*m
\mbfscrf#*m
\mbfscrg#*m
\mbfscrh#*m
\mbfscri#*m
\mbfscrj#*m
\mbfscrk#*m
\mbfscrl#*m
\mbfscrm#*m
\mbfscrn#*m
\mbfscro#*m
\mbfscrp#*m
\mbfscrq#*m
\mbfscrr#*m
\mbfscrs#*m
\mbfscrt#*m
\mbfscru#*m
\mbfscrv#*m
\mbfscrw#*m
\mbfscrx#*m
\mbfscry#*m
\mbfscrz#*m
\mfrakA#*m
\mfrakB#*m
\mfrakD#*m
\mfrakE#*m
\mfrakF#*m
\mfrakG#*m
\mfrakJ#*m
\mfrakK#*m
\mfrakL#*m
\mfrakM#*m
\mfrakN#*m
\mfrakO#*m
\mfrakP#*m
\mfrakQ#*m
\mfrakS#*m
\mfrakT#*m
\mfrakU#*m
\mfrakV#*m
\mfrakW#*m
\mfrakX#*m
\mfrakY#*m
\mfraka#*m
\mfrakb#*m
\mfrakc#*m
\mfrakd#*m
\mfrake#*m
\mfrakf#*m
\mfrakg#*m
\mfrakh#*m
\mfraki#*m
\mfrakj#*m
\mfrakk#*m
\mfrakl#*m
\mfrakm#*m
\mfrakn#*m
\mfrako#*m
\mfrakp#*m
\mfrakq#*m
\mfrakr#*m
\mfraks#*m
\mfrakt#*m
\mfraku#*m
\mfrakv#*m
\mfrakw#*m
\mfrakx#*m
\mfraky#*m
\mfrakz#*m
\BbbA#*m
\BbbB#*m
\BbbD#*m
\BbbE#*m
\BbbF#*m
\BbbG#*m
\BbbI#*m
\BbbJ#*m
\BbbK#*m
\BbbL#*m
\BbbM#*m
\BbbO#*m
\BbbS#*m
\BbbT#*m
\BbbU#*m
\BbbV#*m
\BbbW#*m
\BbbX#*m
\BbbY#*m
\Bbba#*m
\Bbbb#*m
\Bbbc#*m
\Bbbd#*m
\Bbbe#*m
\Bbbf#*m
\Bbbg#*m
\Bbbh#*m
\Bbbi#*m
\Bbbj#*m
\Bbbk#*m
\Bbbl#*m
\Bbbm#*m
\Bbbn#*m
\Bbbo#*m
\Bbbp#*m
\Bbbq#*m
\Bbbr#*m
\Bbbs#*m
\Bbbt#*m
\Bbbu#*m
\Bbbv#*m
\Bbbw#*m
\Bbbx#*m
\Bbby#*m
\Bbbz#*m
\mbffrakA#*m
\mbffrakB#*m
\mbffrakC#*m
\mbffrakD#*m
\mbffrakE#*m
\mbffrakF#*m
\mbffrakG#*m
\mbffrakH#*m
\mbffrakI#*m
\mbffrakJ#*m
\mbffrakK#*m
\mbffrakL#*m
\mbffrakM#*m
\mbffrakN#*m
\mbffrakO#*m
\mbffrakP#*m
\mbffrakQ#*m
\mbffrakR#*m
\mbffrakS#*m
\mbffrakT#*m
\mbffrakU#*m
\mbffrakV#*m
\mbffrakW#*m
\mbffrakX#*m
\mbffrakY#*m
\mbffrakZ#*m
\mbffraka#*m
\mbffrakb#*m
\mbffrakc#*m
\mbffrakd#*m
\mbffrake#*m
\mbffrakf#*m
\mbffrakg#*m
\mbffrakh#*m
\mbffraki#*m
\mbffrakj#*m
\mbffrakk#*m
\mbffrakl#*m
\mbffrakm#*m
\mbffrakn#*m
\mbffrako#*m
\mbffrakp#*m
\mbffrakq#*m
\mbffrakr#*m
\mbffraks#*m
\mbffrakt#*m
\mbffraku#*m
\mbffrakv#*m
\mbffrakw#*m
\mbffrakx#*m
\mbffraky#*m
\mbffrakz#*m
\msansA#*m
\msansB#*m
\msansC#*m
\msansD#*m
\msansE#*m
\msansF#*m
\msansG#*m
\msansH#*m
\msansI#*m
\msansJ#*m
\msansK#*m
\msansL#*m
\msansM#*m
\msansN#*m
\msansO#*m
\msansP#*m
\msansQ#*m
\msansR#*m
\msansS#*m
\msansT#*m
\msansU#*m
\msansV#*m
\msansW#*m
\msansX#*m
\msansY#*m
\msansZ#*m
\msansa#*m
\msansb#*m
\msansc#*m
\msansd#*m
\msanse#*m
\msansf#*m
\msansg#*m
\msansh#*m
\msansi#*m
\msansj#*m
\msansk#*m
\msansl#*m
\msansm#*m
\msansn#*m
\msanso#*m
\msansp#*m
\msansq#*m
\msansr#*m
\msanss#*m
\msanst#*m
\msansu#*m
\msansv#*m
\msansw#*m
\msansx#*m
\msansy#*m
\msansz#*m
\mbfsansA#*m
\mbfsansB#*m
\mbfsansC#*m
\mbfsansD#*m
\mbfsansE#*m
\mbfsansF#*m
\mbfsansG#*m
\mbfsansH#*m
\mbfsansI#*m
\mbfsansJ#*m
\mbfsansK#*m
\mbfsansL#*m
\mbfsansM#*m
\mbfsansN#*m
\mbfsansO#*m
\mbfsansP#*m
\mbfsansQ#*m
\mbfsansR#*m
\mbfsansS#*m
\mbfsansT#*m
\mbfsansU#*m
\mbfsansV#*m
\mbfsansW#*m
\mbfsansX#*m
\mbfsansY#*m
\mbfsansZ#*m
\mbfsansa#*m
\mbfsansb#*m
\mbfsansc#*m
\mbfsansd#*m
\mbfsanse#*m
\mbfsansf#*m
\mbfsansg#*m
\mbfsansh#*m
\mbfsansi#*m
\mbfsansj#*m
\mbfsansk#*m
\mbfsansl#*m
\mbfsansm#*m
\mbfsansn#*m
\mbfsanso#*m
\mbfsansp#*m
\mbfsansq#*m
\mbfsansr#*m
\mbfsanss#*m
\mbfsanst#*m
\mbfsansu#*m
\mbfsansv#*m
\mbfsansw#*m
\mbfsansx#*m
\mbfsansy#*m
\mbfsansz#*m
\mitsansA#*m
\mitsansB#*m
\mitsansC#*m
\mitsansD#*m
\mitsansE#*m
\mitsansF#*m
\mitsansG#*m
\mitsansH#*m
\mitsansI#*m
\mitsansJ#*m
\mitsansK#*m
\mitsansL#*m
\mitsansM#*m
\mitsansN#*m
\mitsansO#*m
\mitsansP#*m
\mitsansQ#*m
\mitsansR#*m
\mitsansS#*m
\mitsansT#*m
\mitsansU#*m
\mitsansV#*m
\mitsansW#*m
\mitsansX#*m
\mitsansY#*m
\mitsansZ#*m
\mitsansa#*m
\mitsansb#*m
\mitsansc#*m
\mitsansd#*m
\mitsanse#*m
\mitsansf#*m
\mitsansg#*m
\mitsansh#*m
\mitsansi#*m
\mitsansj#*m
\mitsansk#*m
\mitsansl#*m
\mitsansm#*m
\mitsansn#*m
\mitsanso#*m
\mitsansp#*m
\mitsansq#*m
\mitsansr#*m
\mitsanss#*m
\mitsanst#*m
\mitsansu#*m
\mitsansv#*m
\mitsansw#*m
\mitsansx#*m
\mitsansy#*m
\mitsansz#*m
\mbfitsansA#*m
\mbfitsansB#*m
\mbfitsansC#*m
\mbfitsansD#*m
\mbfitsansE#*m
\mbfitsansF#*m
\mbfitsansG#*m
\mbfitsansH#*m
\mbfitsansI#*m
\mbfitsansJ#*m
\mbfitsansK#*m
\mbfitsansL#*m
\mbfitsansM#*m
\mbfitsansN#*m
\mbfitsansO#*m
\mbfitsansP#*m
\mbfitsansQ#*m
\mbfitsansR#*m
\mbfitsansS#*m
\mbfitsansT#*m
\mbfitsansU#*m
\mbfitsansV#*m
\mbfitsansW#*m
\mbfitsansX#*m
\mbfitsansY#*m
\mbfitsansZ#*m
\mbfitsansa#*m
\mbfitsansb#*m
\mbfitsansc#*m
\mbfitsansd#*m
\mbfitsanse#*m
\mbfitsansf#*m
\mbfitsansg#*m
\mbfitsansh#*m
\mbfitsansi#*m
\mbfitsansj#*m
\mbfitsansk#*m
\mbfitsansl#*m
\mbfitsansm#*m
\mbfitsansn#*m
\mbfitsanso#*m
\mbfitsansp#*m
\mbfitsansq#*m
\mbfitsansr#*m
\mbfitsanss#*m
\mbfitsanst#*m
\mbfitsansu#*m
\mbfitsansv#*m
\mbfitsansw#*m
\mbfitsansx#*m
\mbfitsansy#*m
\mbfitsansz#*m
\mttA#*m
\mttB#*m
\mttC#*m
\mttD#*m
\mttE#*m
\mttF#*m
\mttG#*m
\mttH#*m
\mttI#*m
\mttJ#*m
\mttK#*m
\mttL#*m
\mttM#*m
\mttN#*m
\mttO#*m
\mttP#*m
\mttQ#*m
\mttR#*m
\mttS#*m
\mttT#*m
\mttU#*m
\mttV#*m
\mttW#*m
\mttX#*m
\mttY#*m
\mttZ#*m
\mtta#*m
\mttb#*m
\mttc#*m
\mttd#*m
\mtte#*m
\mttf#*m
\mttg#*m
\mtth#*m
\mtti#*m
\mttj#*m
\mttk#*m
\mttl#*m
\mttm#*m
\mttn#*m
\mtto#*m
\mttp#*m
\mttq#*m
\mttr#*m
\mtts#*m
\mttt#*m
\mttu#*m
\mttv#*m
\mttw#*m
\mttx#*m
\mtty#*m
\mttz#*m
\imath#*m
\jmath#*m
\mbfAlpha#*m
\mbfBeta#*m
\mbfGamma#*m
\mbfDelta#*m
\mbfEpsilon#*m
\mbfZeta#*m
\mbfEta#*m
\mbfTheta#*m
\mbfIota#*m
\mbfKappa#*m
\mbfLambda#*m
\mbfMu#*m
\mbfNu#*m
\mbfXi#*m
\mbfOmicron#*m
\mbfPi#*m
\mbfRho#*m
\mbfvarTheta#*m
\mbfSigma#*m
\mbfTau#*m
\mbfUpsilon#*m
\mbfPhi#*m
\mbfChi#*m
\mbfPsi#*m
\mbfOmega#*m
\mbfnabla#*m
\mbfalpha#*m
\mbfbeta#*m
\mbfgamma#*m
\mbfdelta#*m
\mbfepsilon#*m
\mbfzeta#*m
\mbfeta#*m
\mbftheta#*m
\mbfiota#*m
\mbfkappa#*m
\mbflambda#*m
\mbfmu#*m
\mbfnu#*m
\mbfxi#*m
\mbfomicron#*m
\mbfpi#*m
\mbfrho#*m
\mbfvarsigma#*m
\mbfsigma#*m
\mbftau#*m
\mbfupsilon#*m
\mbfvarphi#*m
\mbfchi#*m
\mbfpsi#*m
\mbfomega#*m
\mbfpartial#*m
\mbfvarepsilon#*m
\mbfvartheta#*m
\mbfvarkappa#*m
\mbfphi#*m
\mbfvarrho#*m
\mbfvarpi#*m
\mitAlpha#*m
\mitBeta#*m
\mitGamma#*m
\mitDelta#*m
\mitEpsilon#*m
\mitZeta#*m
\mitEta#*m
\mitTheta#*m
\mitIota#*m
\mitKappa#*m
\mitLambda#*m
\mitMu#*m
\mitNu#*m
\mitXi#*m
\mitOmicron#*m
\mitPi#*m
\mitRho#*m
\mitvarTheta#*m
\mitSigma#*m
\mitTau#*m
\mitUpsilon#*m
\mitPhi#*m
\mitChi#*m
\mitPsi#*m
\mitOmega#*m
\mitnabla#*m
\mitalpha#*m
\mitbeta#*m
\mitgamma#*m
\mitdelta#*m
\mitepsilon#*m
\mitzeta#*m
\miteta#*m
\mittheta#*m
\mitiota#*m
\mitkappa#*m
\mitlambda#*m
\mitmu#*m
\mitnu#*m
\mitxi#*m
\mitomicron#*m
\mitpi#*m
\mitrho#*m
\mitvarsigma#*m
\mitsigma#*m
\mittau#*m
\mitupsilon#*m
\mitphi#*m
\mitchi#*m
\mitpsi#*m
\mitomega#*m
\mitpartial#*m
\mitvarepsilon#*m
\mitvartheta#*m
\mitvarkappa#*m
\mitvarphi#*m
\mitvarrho#*m
\mitvarpi#*m
\mbfitAlpha#*m
\mbfitBeta#*m
\mbfitGamma#*m
\mbfitDelta#*m
\mbfitEpsilon#*m
\mbfitZeta#*m
\mbfitEta#*m
\mbfitTheta#*m
\mbfitIota#*m
\mbfitKappa#*m
\mbfitLambda#*m
\mbfitMu#*m
\mbfitNu#*m
\mbfitXi#*m
\mbfitOmicron#*m
\mbfitPi#*m
\mbfitRho#*m
\mbfitvarTheta#*m
\mbfitSigma#*m
\mbfitTau#*m
\mbfitUpsilon#*m
\mbfitPhi#*m
\mbfitChi#*m
\mbfitPsi#*m
\mbfitOmega#*m
\mbfitnabla#*m
\mbfitalpha#*m
\mbfitbeta#*m
\mbfitgamma#*m
\mbfitdelta#*m
\mbfitepsilon#*m
\mbfitzeta#*m
\mbfiteta#*m
\mbfittheta#*m
\mbfitiota#*m
\mbfitkappa#*m
\mbfitlambda#*m
\mbfitmu#*m
\mbfitnu#*m
\mbfitxi#*m
\mbfitomicron#*m
\mbfitpi#*m
\mbfitrho#*m
\mbfitvarsigma#*m
\mbfitsigma#*m
\mbfittau#*m
\mbfitupsilon#*m
\mbfitphi#*m
\mbfitchi#*m
\mbfitpsi#*m
\mbfitomega#*m
\mbfitpartial#*m
\mbfitvarepsilon#*m
\mbfitvartheta#*m
\mbfitvarkappa#*m
\mbfitvarphi#*m
\mbfitvarrho#*m
\mbfitvarpi#*m
\mbfsansAlpha#*m
\mbfsansBeta#*m
\mbfsansGamma#*m
\mbfsansDelta#*m
\mbfsansEpsilon#*m
\mbfsansZeta#*m
\mbfsansEta#*m
\mbfsansTheta#*m
\mbfsansIota#*m
\mbfsansKappa#*m
\mbfsansLambda#*m
\mbfsansMu#*m
\mbfsansNu#*m
\mbfsansXi#*m
\mbfsansOmicron#*m
\mbfsansPi#*m
\mbfsansRho#*m
\mbfsansvarTheta#*m
\mbfsansSigma#*m
\mbfsansTau#*m
\mbfsansUpsilon#*m
\mbfsansPhi#*m
\mbfsansChi#*m
\mbfsansPsi#*m
\mbfsansOmega#*m
\mbfsansnabla#*m
\mbfsansalpha#*m
\mbfsansbeta#*m
\mbfsansgamma#*m
\mbfsansdelta#*m
\mbfsansepsilon#*m
\mbfsanszeta#*m
\mbfsanseta#*m
\mbfsanstheta#*m
\mbfsansiota#*m
\mbfsanskappa#*m
\mbfsanslambda#*m
\mbfsansmu#*m
\mbfsansnu#*m
\mbfsansxi#*m
\mbfsansomicron#*m
\mbfsanspi#*m
\mbfsansrho#*m
\mbfsansvarsigma#*m
\mbfsanssigma#*m
\mbfsanstau#*m
\mbfsansupsilon#*m
\mbfsansphi#*m
\mbfsanschi#*m
\mbfsanspsi#*m
\mbfsansomega#*m
\mbfsanspartial#*m
\mbfsansvarepsilon#*m
\mbfsansvartheta#*m
\mbfsansvarkappa#*m
\mbfsansvarphi#*m
\mbfsansvarrho#*m
\mbfsansvarpi#*m
\mbfitsansAlpha#*m
\mbfitsansBeta#*m
\mbfitsansGamma#*m
\mbfitsansDelta#*m
\mbfitsansEpsilon#*m
\mbfitsansZeta#*m
\mbfitsansEta#*m
\mbfitsansTheta#*m
\mbfitsansIota#*m
\mbfitsansKappa#*m
\mbfitsansLambda#*m
\mbfitsansMu#*m
\mbfitsansNu#*m
\mbfitsansXi#*m
\mbfitsansOmicron#*m
\mbfitsansPi#*m
\mbfitsansRho#*m
\mbfitsansvarTheta#*m
\mbfitsansSigma#*m
\mbfitsansTau#*m
\mbfitsansUpsilon#*m
\mbfitsansPhi#*m
\mbfitsansChi#*m
\mbfitsansPsi#*m
\mbfitsansOmega#*m
\mbfitsansnabla#*m
\mbfitsansalpha#*m
\mbfitsansbeta#*m
\mbfitsansgamma#*m
\mbfitsansdelta#*m
\mbfitsansepsilon#*m
\mbfitsanszeta#*m
\mbfitsanseta#*m
\mbfitsanstheta#*m
\mbfitsansiota#*m
\mbfitsanskappa#*m
\mbfitsanslambda#*m
\mbfitsansmu#*m
\mbfitsansnu#*m
\mbfitsansxi#*m
\mbfitsansomicron#*m
\mbfitsanspi#*m
\mbfitsansrho#*m
\mbfitsansvarsigma#*m
\mbfitsanssigma#*m
\mbfitsanstau#*m
\mbfitsansupsilon#*m
\mbfitsansphi#*m
\mbfitsanschi#*m
\mbfitsanspsi#*m
\mbfitsansomega#*m
\mbfitsanspartial#*m
\mbfitsansvarepsilon#*m
\mbfitsansvartheta#*m
\mbfitsansvarkappa#*m
\mbfitsansvarphi#*m
\mbfitsansvarrho#*m
\mbfitsansvarpi#*m
\mbfDigamma#*m
\mbfdigamma#*m
\mbfzero#*m
\mbfone#*m
\mbftwo#*m
\mbfthree#*m
\mbffour#*m
\mbffive#*m
\mbfsix#*m
\mbfseven#*m
\mbfeight#*m
\mbfnine#*m
\Bbbzero#*m
\Bbbone#*m
\Bbbtwo#*m
\Bbbthree#*m
\Bbbfour#*m
\Bbbfive#*m
\Bbbsix#*m
\Bbbseven#*m
\Bbbeight#*m
\Bbbnine#*m
\msanszero#*m
\msansone#*m
\msanstwo#*m
\msansthree#*m
\msansfour#*m
\msansfive#*m
\msanssix#*m
\msansseven#*m
\msanseight#*m
\msansnine#*m
\mbfsanszero#*m
\mbfsansone#*m
\mbfsanstwo#*m
\mbfsansthree#*m
\mbfsansfour#*m
\mbfsansfive#*m
\mbfsanssix#*m
\mbfsansseven#*m
\mbfsanseight#*m
\mbfsansnine#*m
\mttzero#*m
\mttone#*m
\mtttwo#*m
\mttthree#*m
\mttfour#*m
\mttfive#*m
\mttsix#*m
\mttseven#*m
\mtteight#*m
\mttnine#*m
\arabicmaj#*m
\arabichad#*m
